# Maintainer: konrad@diva.exchange
#

version: "3.7"
services:
  ${I2P_CONTAINER_NAME}:
    image: ${I2PD_IMAGE_NAME}:${I2PD_IMAGE_TAG}
    container_name: ${I2P_CONTAINER_NAME}
    expose:
      - ${CONST_I2PD_DOCKER_WEBCONSOLE_PORT} # i2p webconsole
    ports:
      - target: ${CONST_I2PD_DOCKER_WEBCONSOLE_PORT}
        published: ${I2PD_WEBCONSOLE_PORT}
        protocol: tcp
        mode: host
    environment:
      ENABLE_TUNNELS: "1"
    volumes:
      - type: bind
        source: ${PWD}/tunnels.conf.d
        target: /home/i2pd/tunnels.source.conf.d
      - type: volume
        source: i2p-${I2P_CONTAINER_NAME}
        target: /home/i2pd/
    networks:
      ${NETWORK_NAME}:
        ipv4_address: ${IP_I2P}
    extra_hosts:
      - "iroha:${IP_IROHA}"

  ${IROHA_CONTAINER_NAME}:
    image: ${IROHA_IMAGE_NAME}:${IROHA_IMAGE_TAG}
    container_name: i2p-${IROHA_CONTAINER_NAME}
    environment:
      NAME_KEY: ${NAME_KEY}
      IP_IROHA_NODE: ${IP_IROHA_NODE}
      TYPE: I2P
    volumes:
      - type: volume
        source: i2p-${IROHA_CONTAINER_NAME}
        target: /opt/iroha
    networks:
      ${NETWORK_NAME}:
        ipv4_address: ${IP_IROHA}

  ${IROHA_NODE_CONTAINER_NAME}:
    image: ${IROHA_NODE_IMAGE_NAME}:i2p
    container_name: i2p-${IROHA_NODE_CONTAINER_NAME}
    environment:
      NAME_KEY: ${NAME_KEY}
      TYPE: I2P
      IP: ${IP_IROHA_NODE}
      PORT: 10001
    networks:
      ${NETWORK_NAME}:
        ipv4_address: ${IP_IROHA_NODE}
    extra_hosts:
      - "i2p:${IP_I2P}"

networks:
  ${NETWORK_NAME}:
    external: true

volumes:
  i2p-${I2P_CONTAINER_NAME}:
    name: i2p-${I2P_CONTAINER_NAME}
  i2p-${IROHA_CONTAINER_NAME}:
    name: i2p-${IROHA_CONTAINER_NAME}
