#
#    Copyright (C) 2020 diva.exchange
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
#
#    Author/Maintainer: Konrad Bächler <konrad@diva.exchange>
#

version: "3.7"
services:
  ${IROHA_NODE_CONTAINER_NAME}:
    image: divax/iroha-node:latest
    container_name: p2p-${IROHA_NODE_CONTAINER_NAME}
    environment:
      IDENT_INSTANCE: ${IDENT_INSTANCE}
      TYPE: P2P
    volumes:
      - type: volume
        source: p2p-${IROHA_NODE_CONTAINER_NAME}
        target: /home/node
    networks:
      bridge:
        aliases:
          - p2p-${IROHA_NODE_CONTAINER_NAME}

  ${IROHA_CONTAINER_NAME}:
    image: divax/iroha:latest
    container_name: p2p-${IROHA_CONTAINER_NAME}
    expose:
      - 50051 # Iroha torii port
      - 5432 # Postgres port
    ports:
      - "${IROHA_TORII_PORT}:50051/tcp"
      - "${IROHA_POSTGRES_PORT}:5432/tcp"
    environment:
      IDENT_INSTANCE: ${IDENT_INSTANCE}
      NAME_KEY: "${NAME_KEY}"
      BLOCKCHAIN_NETWORK: "${BLOCKCHAIN_NETWORK}"
      HOST_IROHA_NODE: p2p-${IROHA_NODE_CONTAINER_NAME}
    volumes:
      - type: volume
        source: p2p-${IROHA_CONTAINER_NAME}
        target: /opt/iroha
    networks:
      bridge:

networks:
  bridge:
    name: diva-p2p-stun-ice

volumes:
  p2p-${IROHA_CONTAINER_NAME}:
    name: p2p-${IROHA_CONTAINER_NAME}
  p2p-${IROHA_NODE_CONTAINER_NAME}:
    name: p2p-${IROHA_NODE_CONTAINER_NAME}
