# Maintainer: konrad@diva.exchange
#
# use the supplied ${PROJECT_PATH}/build.sh to build the images
# use the supplied ${PROJECT_PATH}/up.sh to start the containers

version: "3.7"
services:
  ${I2P_CONTAINER_NAME}:
    image: ${I2PD_IMAGE_NAME}:${I2PD_IMAGE_TAG}
    container_name: ${I2P_CONTAINER_NAME}
    expose:
      - ${CONST_I2PD_DOCKER_WEBCONSOLE_PORT} # i2p webconsole
    ports:
      - target: ${CONST_I2PD_DOCKER_WEBCONSOLE_PORT}
        published: ${I2PD_WEBCONSOLE_PORT}
        protocol: tcp
        mode: host
    environment:
      ENABLE_TUNNELS: "1"
    volumes:
      - type: bind
        source: ${PWD}/tunnels.conf.d
        target: /home/i2pd/tunnels.source.conf.d
      - type: volume
        source: ${I2P_CONTAINER_NAME}_i2pd
        target: /home/i2pd/
    networks:
      ${NETWORK_NAME}:
        ipv4_address: ${IP_I2P}
    extra_hosts:
      - "iroha:${IP_IROHA}"

  ${IROHA_CONTAINER_NAME}:
    image: ${IROHA_IMAGE_NAME}:${IROHA_IMAGE_TAG}
    container_name: ${IROHA_CONTAINER_NAME}
    environment:
      NAME_KEY: ${NAME_KEY}
      IP_IROHA_PROXY: ${IP_IROHA_PROXY}
    volumes:
      - type: volume
        source: ${IROHA_CONTAINER_NAME}_iroha
        target: /opt/iroha
    networks:
      ${NETWORK_NAME}:
        ipv4_address: ${IP_IROHA}
    extra_hosts:
      - "iroha-proxy:${IP_IROHA_PROXY}"

  ${IROHA_PROXY_CONTAINER_NAME}:
    image: ${IROHA_PROXY_IMAGE_NAME}:${IROHA_PROXY_IMAGE_TAG}
    container_name: ${IROHA_PROXY_CONTAINER_NAME}
    networks:
      ${NETWORK_NAME}:
        ipv4_address: ${IP_IROHA_PROXY}
    extra_hosts:
      - "i2p:${IP_I2P}"

networks:
  ${NETWORK_NAME}:
    external: true

volumes:
  ${I2P_CONTAINER_NAME}_i2pd:
    name: ${I2P_CONTAINER_NAME}_i2pd
  ${IROHA_CONTAINER_NAME}_iroha:
    name: ${IROHA_CONTAINER_NAME}_iroha
