#
# Copyright (C) 2020 diva.exchange
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Author/Maintainer: Konrad Bächler <konrad@diva.exchange>
#

version: "3.7"
services:
  i2p.testnet.diva.i2p:
    container_name: i2p.testnet.diva.i2p
    image: divax/i2p:latest
    restart: unless-stopped
    environment:
      ENABLE_TUNNELS: 1
    volumes:
      - ../tunnels.conf.d/testnet:/home/i2pd/tunnels.source.conf.d/
      - i2p.testnet.diva.i2p:/home/i2pd/data/
    networks:
      network.testnet.diva.i2p:
        ipv4_address: 172.20.101.200

  postgres.testnet.diva.i2p:
    container_name: postgres.testnet.diva.i2p
    image: postgres:alpine
    command: -c max_prepared_transactions=100
    restart: unless-stopped
    environment:
      POSTGRES_USER: iroha
      POSTGRES_PASSWORD: iroha
    volumes:
      - postgres.testnet.diva.i2p:/var/lib/postgresql/data/
    networks:
      network.testnet.diva.i2p:
        ipv4_address: 172.20.101.2

  node.testnet.diva.i2p:
    container_name: node.testnet.diva.i2p
    image: divax/iroha-node:api-ws
    restart: unless-stopped
    environment:
      NODE_ENV: ${NODE_ENV:-development}
      TORII: 172.20.101.3:50051
      CREATOR_ACCOUNT: diva@testnet
      I2P_HOSTNAME: 172.20.101.200
      I2P_HTTP_PROXY_PORT: 4444
      I2P_WEBCONSOLE_PORT: 7070
    volumes:
      - tn1.diva.i2p:/tmp/iroha/
      - node.testnet.diva.i2p:/home/node/data/
    networks:
      network.testnet.diva.i2p:
        ipv4_address: 172.20.101.201

  tn1.diva.i2p:
    container_name: tn1.diva.i2p
    image: divax/iroha:latest
    restart: unless-stopped
    stop_grace_period: 30s
    depends_on:
      - postgres.testnet.diva.i2p
    environment:
      NAME_CONTAINER_POSTGRES: postgres.testnet.diva.i2p
      NAME_PEER: tn1
      BLOCKCHAIN_NETWORK: testnet
      IP_HTTP_PROXY: 172.20.101.200
      PORT_HTTP_PROXY: 4444
      NO_PROXY: tn1.diva.i2p,tn2.diva.i2p,tn3.diva.i2p
    volumes:
      - tn1.diva.i2p:/opt/iroha/
    networks:
      network.testnet.diva.i2p:
        ipv4_address: 172.20.101.3
    extra_hosts:
      - tn1.diva.i2p:172.20.101.3
      - tn2.diva.i2p:172.20.101.4
      - tn3.diva.i2p:172.20.101.5

  tn2.diva.i2p:
    container_name: tn2.diva.i2p
    image: divax/iroha:latest
    restart: unless-stopped
    stop_grace_period: 30s
    depends_on:
      - postgres.testnet.diva.i2p
    environment:
      NAME_CONTAINER_POSTGRES: postgres.testnet.diva.i2p
      NAME_PEER: tn2
      BLOCKCHAIN_NETWORK: testnet
      IP_HTTP_PROXY: 172.20.101.200
      PORT_HTTP_PROXY: 4444
      NO_PROXY: tn1.diva.i2p,tn2.diva.i2p,tn3.diva.i2p
    volumes:
      - tn2.diva.i2p:/opt/iroha/
    networks:
      network.testnet.diva.i2p:
        ipv4_address: 172.20.101.4
    extra_hosts:
      - tn1.diva.i2p:172.20.101.3
      - tn2.diva.i2p:172.20.101.4
      - tn3.diva.i2p:172.20.101.5

  tn3.diva.i2p:
    container_name: tn3.diva.i2p
    image: divax/iroha:latest
    restart: unless-stopped
    stop_grace_period: 30s
    depends_on:
      - postgres.testnet.diva.i2p
    environment:
      NAME_CONTAINER_POSTGRES: postgres.testnet.diva.i2p
      NAME_PEER: tn3
      BLOCKCHAIN_NETWORK: testnet
      IP_HTTP_PROXY: 172.20.101.200
      PORT_HTTP_PROXY: 4444
      NO_PROXY: tn1.diva.i2p,tn2.diva.i2p,tn3.diva.i2p
    volumes:
      - tn3.diva.i2p:/opt/iroha/
    networks:
      network.testnet.diva.i2p:
        ipv4_address: 172.20.101.5
    extra_hosts:
      - tn1.diva.i2p:172.20.101.3
      - tn2.diva.i2p:172.20.101.4
      - tn3.diva.i2p:172.20.101.5

  explorer.testnet.diva.i2p:
    container_name: explorer.testnet.diva.i2p
    image: divax/iroha-explorer:latest
    restart: unless-stopped
    depends_on:
      - postgres.testnet.diva.i2p
      - tn1.diva.i2p
    environment:
      IP_EXPLORER: 0.0.0.0
      PORT_EXPLORER: 3920
      PATH_IROHA: /tmp/iroha/
    ports:
      - 3920:3920
    volumes:
      - tn1.diva.i2p:/tmp/iroha/:ro
    networks:
      network.testnet.diva.i2p:
        ipv4_address: 172.20.101.100

networks:
  network.testnet.diva.i2p:
    name: network.testnet.diva.i2p
    ipam:
      driver: default
      config:
        - subnet: 172.20.101.0/24

volumes:
  i2p.testnet.diva.i2p:
    name: i2p.testnet.diva.i2p
  postgres.testnet.diva.i2p:
    name: postgres.testnet.diva.i2p
  node.testnet.diva.i2p:
    name: node.testnet.diva.i2p
  tn1.diva.i2p:
    name: tn1.diva.i2p
  tn2.diva.i2p:
    name: tn2.diva.i2p
  tn3.diva.i2p:
    name: tn3.diva.i2p
