#
# Copyright (C) 2020 diva.exchange
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Author/Maintainer: Konrad Bächler <konrad@diva.exchange>
#

version: "3.7"
services:
  i2p.testnet.diva.i2p:
    container_name: i2p.testnet.diva.i2p
    image: divax/i2p:latest
    restart: unless-stopped
    environment:
      ENABLE_TUNNELS: 1
    volumes:
      - i2p.testnet.diva.i2p:/home/i2pd/
      - ../tunnels.conf.d/testnet:/home/i2pd/tunnels.source.conf.d/
    networks:
      network.testnet.diva.i2p:
        ipv4_address: 172.29.101.10

networks:
  network.testnet.diva.i2p:
    name: network.testnet.diva.i2p
    ipam:
      driver: default
      config:
        - subnet: 172.29.101.0/24

volumes:
  i2p.testnet.diva.i2p:
    name: i2p.testnet.diva.i2p
