#
# Copyright (C) 2020 diva.exchange
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU Affero General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Affero General Public License for more details.
#
# You should have received a copy of the GNU Affero General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.
#
# Author/Maintainer: Konrad Bächler <konrad@diva.exchange>
#

version: "3.7"
services:
  postgres.testnet.diva.local:
    container_name: postgres.testnet.diva.local
    image: postgres:alpine
    command: -c max_prepared_transactions=100
    restart: unless-stopped
    environment:
      POSTGRES_USER: iroha
      POSTGRES_PASSWORD: iroha
    volumes:
      - postgres.testnet.diva.local:/var/lib/postgresql/data/
    networks:
      network.testnet.diva.local:
        ipv4_address: 172.29.101.2

  n1.testnet.diva.local:
    container_name: n1.testnet.diva.local
    image: divax/iroha:${TAG:-latest}
    restart: unless-stopped
    environment:
      NAME_CONTAINER_POSTGRES: postgres.testnet.diva.local
      NAME_PEER: n1
      BLOCKCHAIN_NETWORK: diva-local
    volumes:
      - n1.testnet.diva.local:/opt/iroha/
    networks:
      network.testnet.diva.local:
        ipv4_address: 172.29.101.3
    extra_hosts:
      - n1.testnet.diva.i2p:172.29.101.3
      - n2.testnet.diva.i2p:172.29.101.4
      - n3.testnet.diva.i2p:172.29.101.5

  n2.testnet.diva.local:
    container_name: n2.testnet.diva.local
    image: divax/iroha:${TAG:-latest}
    restart: unless-stopped
    environment:
      NAME_CONTAINER_POSTGRES: postgres.testnet.diva.local
      NAME_PEER: n2
      BLOCKCHAIN_NETWORK: diva-local
    volumes:
      - n2.testnet.diva.local:/opt/iroha/
    networks:
      network.testnet.diva.local:
        ipv4_address: 172.29.101.4
    extra_hosts:
      - n1.testnet.diva.i2p:172.29.101.3
      - n2.testnet.diva.i2p:172.29.101.4
      - n3.testnet.diva.i2p:172.29.101.5

  n3.testnet.diva.local:
    container_name: n3.testnet.diva.local
    image: divax/iroha:${TAG:-latest}
    restart: unless-stopped
    environment:
      NAME_CONTAINER_POSTGRES: postgres.testnet.diva.local
      NAME_PEER: n3
      BLOCKCHAIN_NETWORK: diva-local
    volumes:
      - n3.testnet.diva.local:/opt/iroha/
    networks:
      network.testnet.diva.local:
        ipv4_address: 172.29.101.5
    extra_hosts:
      - n1.testnet.diva.i2p:172.29.101.3
      - n2.testnet.diva.i2p:172.29.101.4
      - n3.testnet.diva.i2p:172.29.101.5

  explorer.testnet.diva.local:
    container_name: explorer.testnet.diva.local
    image: divax/iroha-explorer:latest
    restart: unless-stopped
    environment:
      IP_EXPLORER: 0.0.0.0
      PORT_EXPLORER: 3920
      PATH_IROHA: /tmp/iroha/
    ports:
      - 3929:3920
    volumes:
      - n3.testnet.diva.local:/tmp/iroha/:ro
      - explorer.testnet.diva.local:/home/node/
    networks:
      network.testnet.diva.local:
        ipv4_address: 172.29.101.100

networks:
  network.testnet.diva.local:
    internal: true
    name: network.testnet.diva.local
    ipam:
      driver: default
      config:
        - subnet: 172.29.101.0/24

volumes:
  n1.testnet.diva.local:
    name: n1.testnet.diva.local
  n2.testnet.diva.local:
    name: n2.testnet.diva.local
  n3.testnet.diva.local:
    name: n3.testnet.diva.local
  postgres.testnet.diva.local:
    name: postgres.testnet.diva.local
  explorer.testnet.diva.local:
    name: explorer.testnet.diva.local
